### ISSUE TITLE
Release tag 1.0.7 as standard format v1.0.7 tag

### ISSUE THREAD

**Issue by hardikmodha** [undefinedlabs/go-mpatch#16]
Hi folks,

Thank you for your continuous effort in maintaining this project. I can see that recently 1.0.7 was released with ARM64 support but when I try to upgrade my existing `v1.0.6` to `v1.0.7` then I get the following error.  

go.mod
```
github.com/undefinedlabs/go-mpatch v1.0.7
```

error: 
```
go: downloading github.com/undefinedlabs/go-mpatch v1.0.7
<my_project> imports
	github.com/undefinedlabs/go-mpatch: reading github.com/undefinedlabs/go-mpatch/go.mod at revision v1.0.7: unknown revision v1.0.7
```
I can easily work around it by providing the tag as "1.0.7" it will work but it gets converted to a [pseudo version](https://go.dev/ref/mod#pseudo-versions). 

go.mod
```
github.com/undefinedlabs/go-mpatch "1.0.7" -> github.com/undefinedlabs/go-mpatch v1.0.7-0.20230127124832-03333c653ab4
```

**Ask**:

Can we release the tag in standard format in `v1.0.7`? Reference: https://go.dev/ref/mod#version-queries. Thanks in advance 🙌

**Comment by hardikmodha** [comment]
Hi folks, Any update on this? @tonyredondo

**Comment by sefasenturk95** [comment]
Bump..

**Comment by tonyredondo** [comment]
Sorry for the delay, I'm not longer working actively in this project. The v1.0.7 tag was created.
