### ISSUE TITLE
Add support to ARM64

### ISSUE THREAD

**Issue by tonyredondo** [undefinedlabs/go-mpatch#2]
We need to bring monkey patching support to AMR64, okteto is compiling in this architecture.

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/77516327-7b2f8a00-6e7a-11ea-8bb1-e8c87c825104.png)

**Comment by drodriguezhdez** [comment]
![image](https://user-images.githubusercontent.com/29516565/77516661-11fc4680-6e7b-11ea-8ec3-e3427897a12f.png)

**Comment by Artoria2e5** [comment]
ARM and ARM64 takes more than one instruction to do the job, as the basic branch `b` instruction takes just an offset. To go anywhere in the address space, you need four instructions of `mov` immediate to set the address to a scratch register, and then a `br` to use the register to set PC. That's... 20 bytes? Should fit anywhere we want it to.

The scratch register choice will be more important in the future with registers coming into the calling convention. 

I don't have any arm machines to test with, so forgive me for leaving a comment here and running away...

**Comment by alhamsya** [comment]
any update for this issue ?

**Comment by tonyredondo** [comment]
> any update for this issue ?

@alhamsya, support has been added in the last release.

**Comment by stefanopallicca-imagicle** [comment]
Tag is wrong, it is 1.0.7 instead of v1.0.7
