### ISSUE TITLE
Unable to Patch Method of Value Receiver Struct

### ISSUE THREAD

**Issue by joez-tkpd** [undefinedlabs/go-mpatch#4]
hi I want to ask how to patch method of (not pointer) value receiver struct? 

for example
```
type User struct {
	id   int
	name string
}

func (u User) GetID() int {
	return u.id
}

func Test_NonPointerStruct(t *testing.T) {
	user := User{123, "Dummy User"}
	expectedID := 999

	p, err := mpatch.PatchInstanceMethodByName(reflect.TypeOf(user), "GetID", func(User) int { return expectedID })
	if err != nil {
		//err = the target and/or redirection doesn't have the same type: func(*User) int != func() int
		t.Error(err)
	}

	defer p.Unpatch()

	id := user.GetID()
	if id != expectedID {
		t.Errorf("expected = %v, actual %v", expectedID, id)
	}
}
```

if we change the replacement function into `func(*User)` it won't patch the real function which is `func(User)`

is there any solution beside changing the method parameter into `func (u *User)GetID() int` ?

and also, maybe it's related to this lines?
https://github.com/undefinedlabs/go-mpatch/blob/1a86426f42a63d2ff56dba366c7024853ee624da/patcher.go#L45-L47

thanks

**Comment by tonyredondo** [comment]
Hello @joez-tkpd thanks, for reporting the issue, a PR was created to handle that scenario.
